export const regionMapping = {
  'Abyan Governorate': 'abyan',
  '‘Adan Governorate': 'aden',
  "Al Bayda' Governorate": 'al bayda',
  "Ad Dali' Governorate": 'al dhale\'e',
  'Al Hudaydah Governorate': 'al hudaydah',
  'Al Jawf Governorate': 'al jawf',
  'Al Mahrah Governorate': 'al maharah',
  'Al Mahwit Governorate': 'al mahwit',
  'Sanʿaʾ': 'amanat al asimah',
  "'Amran Governorate": 'amran',
  'Dhamar Governorate': 'dhamar',
  'Hadhramaut': 'hadramaut',
  'Hajjah Governorate': 'hajjah',
  'Ibb Governorate': 'ibb',
  'Lahij Governorate': 'lahj',
  "Ma'rib Governorate": 'marib',
  'Raymah Governorate': 'raymah',
  'Sanʿaʾ Governorate': 'sana\'a',
  'Shabwah Governorate': 'shabwah',
  'Socotra': 'socotra',
  "Ta'izz Governorate": 'taizz',
};

export const excludedRegions = ['Sa\'dah Governorate'];