# Yemen Market Analysis Configuration

# Directory paths
directories:
  data_dir: 'project/data/'
  processed_data_dir: 'project/data/processed/'
  results_dir: 'results/'
  logs_dir: 'results/logs/'
  external_data_dir: 'external_data/'

# File paths
files:
  spatial_geojson: 'project/data/processed/unified_data.geojson'
  enhanced_geojson: 'project/data/processed/enhanced_unified_data_with_residuals.geojson'
  spatial_analysis_results: 'results/spatial_analysis_results.json'
  ecm_results: 'results/ecm/ecm_analysis_results.json'
  spatial_weights_json: 'results/spatial_weights/spatial_weights.json'
  naturalearth_lowres: 'external_data/naturalearth_lowres/ne_110m_admin_0_countries.shp'

# Analysis parameters
parameters:
  # Time series parameters
  min_common_dates: 20
  lag_periods: 2
  granger_max_lags: 4
  
  # Spatial parameters
  distance_threshold: 200
  min_neighbors: 2
  
  # Statistical thresholds
  stationarity_significance_level: 0.05
  cointegration_significance_level: 0.05
  
  # Model parameters
  ridge_alpha: 1.0
  max_epochs: 1000
  learning_rate: 0.01
  min_regions: 5

  # Commodities to analyze (case-insensitive)
  commodities:
    - 'wheat flour'
    - 'rice'
    - 'vegetable oil'
    - 'sugar'
    - 'diesel'
    - 'petrol'

  # Exchange rate regimes
  exchange_rate_regimes:
    - 'north'
    - 'south'
    - 'unified'
  
  # Exchange rate regime unification
  regimes_to_unify:
    - 'north'
    - 'south'
  new_regime_name: 'unified'

  # Column names
  exchange_rate_regime_column: 'exchange_rate_regime'
  region_identifier: 'admin1'
  time_column: 'date'
  lag_variable: 'usdprice'

  # Spatial weights parameters
  spatial_weights:
    threshold_multiplier: 1

  # Logging configuration
  logging:
    level: 'DEBUG'
    format: '%(asctime)s - %(levelname)s - %(message)s'
