name: Lighthouse CI

on:
  push:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.7.x
      - name: Run Lighthouse CI
        run: lhci autorun